[build]
  command = "npm run build --prefix aquaflow-admin"
  publish = "aquaflow-admin/dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
